# Generated by Django 3.2.9 on 2022-01-10 04:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20220110_0652'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='location',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.location'),
        ),
    ]
