# Generated by Django 3.2.9 on 2022-01-10 17:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_business_location'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='description',
            new_name='about',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='image',
            new_name='photo',
        ),
    ]
