# Generated by Django 3.2.9 on 2022-01-10 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20220110_2026'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='about',
            field=models.TextField(blank=True, max_length=800, null=True),
        ),
    ]
